### ISSUE TITLE
The finance doesn't work at all and return the error 212 on the GetReport method

### ISSUE THREAD

**Issue by elikrief** [beardon/apple-reporter#1]
The finance doesn't work at all and return the error 212
"An unexpected error occurred. Try again later."

**Comment by tyscorp** [comment]
Does it work using the same `userid`/`password`/`vendorNumber` with the [official CLI](https://help.apple.com/itc/appsreporterguide/#/itc21263284f)?

**Comment by elikrief** [comment]
HiThank you for your response.The last request from a few hours ago do works .The code in our side is the same , it looks like something was wrong in your side.Do you know something about it?Would this error occurs in a regular basis or was it a temporary issue that is now fixed?Thanks again for your help

**Comment by tyscorp** [comment]
I would guess that the issue is on Apple's side since it resolved itself. Let me know if it continues to happen and I'll investigate it more thoroughly.
