### ISSUE TITLE
(At least) Sales.getReport endpoint requires a reportVersion parameter

### ISSUE THREAD

**Issue by cyrilchandelier** [beardon/apple-reporter#10]
It was working totally fine yesterday, but today when I try to download my report, I get the following error:
```
AppleReporterError: Please include the version parameter. The latest version for this report is 1_1.
```

I suspect Apple finally shutdown 1_0 (2 months late?) as written in the documentation:
<img width="609" alt="screen shot 2018-06-01 at 11 16 15" src="https://user-images.githubusercontent.com/820515/40857437-01f49d5a-6590-11e8-9ac9-fbbdb8cb8da1.png">

A workaround to make it work locally was to:
- add `reportVersion: "1_1"` to my `reporter.Sales.getReport` options
- add `reportVersion` to the parameters list index.js line 35

from:
```
this.getReport = create('getReport', ['vendorNumber', 'reportType', 'reportSubType', 'dateType', 'date',]);
```

to:
```
this.getReport = create('getReport', ['vendorNumber', 'reportType', 'reportSubType', 'dateType', 'date','reportVersion']);
````

As a result, the downloaded CSV is different (new fields), but this works. 

This is probably not a good solution, but I don't know your codebase enough to fix the issue properly; this API update probably also impact other endpoints, but I'm not using any other one so no idea which one has to change. 

Happy to help with a PR with some guidance.

**Comment by wayneashleyberry** [comment]
I'm having the same issue, glad to know it isn't just me!

@cyrilchandelier that change you suggested works for me as well, why don't you open a PR?
