### ISSUE TITLE
Allow specifying access token 

### ISSUE THREAD

**Issue by zetachang** [beardon/apple-reporter#5]
It seems like Reporter no longer allow email / password and requires [access token](http://help.apple.com/itc/contentreporterguide/en.lproj/static.html#apd2f1f1cfa3).

I've tried adding an `accesstoken` param [here](https://github.com/beardon/apple-reporter/blob/master/lib/index.js#L66) to replace username & password, and it works fine for me.

**Comment by cemulate** [comment]
This is handled in #6 and we'll publish the new version on `npm` (major version bump to `2.0.0`) as soon as its merged.

**Comment by cemulate** [comment]
This is implemented in release 2.0.1, and [published on npm](https://www.npmjs.com/package/apple-reporter)
